### ISSUE TITLE
gc-wip: IPA objects are not written to GC instance whem ipa-adtrust-install executed without --add-sids

### ISSUE THREAD

**Issue by wladich** [abbra/freeipa#44]
1. Documentation should clearly state that without --add-sids no existing users and groups will be available in GC
2. ipa-adtrust-install does display a warning in the beginning of setup process but does not say that existing users will not be copied to GC. IMO it would be nice to display such warning near the message about network ports.
3. globalcatalog.log contains ERROR messages after running ipa-adtrust-install

**Comment by abbra** [comment]
Moved this ticket to https://pagure.io/freeipa/issue/8730
