### ISSUE TITLE
gc-wip: sync daemon does not write cookie to file

### ISSUE THREAD

**Issue by wladich** [abbra/freeipa#50]
After `ipactl restart` ipa-gcsyncd starts "initial sync" again

Version: 4.9.0.dev202010011457+git-0.fc32

Steps to reproduce: 
Ater ipa-server-install:
```
# ipa-adtrust-install -U -a Secret123 --add-sids
...
Configuring Global Catalog synchronization service (ipa-gcsyncd)
  [1/2]: configuring ipa-gcsyncd to start on boot
  [2/2]: start ipa-gcsyncd
Done configuring Global Catalog synchronization service (ipa-gcsyncd).
...

# cat /var/lib/ipa/gc_cookie
cat: /var/lib/ipa/gc_cookie: No such file or directory

# ipactl restart
...
Restarting globalcatalog Service
Restarting ipa-gcsyncd Service
ipa: INFO: The ipactl command was successful

# cat /var/lib/ipa/gc_cookie
cat: /var/lib/ipa/gc_cookie: No such file or directory

# cat /var/log/ipa/globalcatalog.log 
2020-10-08T14:20:04Z	35137	MainThread	ipa-gcsyncd	INFO	LDAP bind...
2020-10-08T14:20:04Z	35137	MainThread	ipa-gcsyncd	INFO	Commencing sync process
2020-10-08T14:20:05Z	35137	MainThread	ipaserver.globalcatalog.gcsyncer	INFO	Initial LDAP dump is done, now synchronizing with GC
2020-10-08T14:26:41Z	35137	MainThread	ipa-gcsyncd	ERROR	syncrepl_poll: LDAP error ({'desc': "Can't contact LDAP server"})
2020-10-08T14:27:22Z	35960	MainThread	ipa-gcsyncd	INFO	LDAP bind...
2020-10-08T14:27:22Z	35960	MainThread	ipa-gcsyncd	INFO	Commencing sync process
2020-10-08T14:27:22Z	35960	MainThread	ipaserver.globalcatalog.gcsyncer	INFO	Initial LDAP dump is done, now synchronizing with GC
```

**Comment by wladich** [comment]
I guess cookie is written to disk only when some event in main instance occurs, which triggers synchronization via syncrepl. But it should be also written after initial data import.

**Comment by flo-renaud** [comment]
I scratched my head for a while before finding the reason for this issue...

The LDAP message sent to signal the end of the refresh phase looks like this:
```
SyncInfoValue:
 refreshDelete=RefreshDelete:
  cookie=master.ipa.test:389#cn=Directory Manager:cn=accounts,dc=ipa,dc=test:(|(objectClass=groupofnames)(objectClass=person))#154
```
but the object SyncInfoValue is not properly parsed and the cookie is lost.

The synchronization daemon is using the library python3-ldap that provides syncrepl. The code in `ldap/syncrepl.py` uses pyasn1 methods to decode the LDAP messages, especially `getComponentByName` (see line 318 in the class [SyncInfoMessage](https://pagure.io/python-ldap/blob/3.0/f/Lib/ldap/syncrepl.py#_301)), and hits a bug in pyasn1: issue [193](https://github.com/python-ldap/python-ldap/issues/193).

There is a workaround in python-ldap 3.3 but unfortunately fedora 32 is still shipped with python-ldap 3.1.0.

**Comment by abbra** [comment]
I built python-ldap with the patch from https://github.com/python-ldap/python-ldap/pull/351

**Comment by abbra** [comment]
@wladich please test the new build and if it is wokring, I'll submit a PR to Fedora with this patch.

**Comment by wladich** [comment]
Now cookie is written to disk after restart, but I still see "Initial LDAP dump is done" in globalcatalog.log (the log file is after running `ipactl restart twice`):
```
# cat /var/lib/ipa/gc_cookie
master1.testrelm.test:389#cn=Directory Manager:cn=accounts,dc=testrelm,dc=test:(|(objectClass=groupofnames)(objectClass=person))#162

# cat /var/log/ipa/globalcatalog.log
2020-10-14T09:25:55Z	33773	MainThread	ipa-gcsyncd	INFO	LDAP bind...
2020-10-14T09:25:55Z	33773	MainThread	ipa-gcsyncd	INFO	Commencing sync process
2020-10-14T09:25:55Z	33773	MainThread	ipaserver.globalcatalog.gcsyncer	INFO	Initial LDAP dump is done, now synchronizing with GC
2020-10-14T09:27:13Z	33773	MainThread	ipa-gcsyncd	ERROR	syncrepl_poll: LDAP error ({'desc': "Can't contact LDAP server"})
2020-10-14T09:27:56Z	34588	MainThread	ipa-gcsyncd	INFO	LDAP bind...
2020-10-14T09:27:56Z	34588	MainThread	ipa-gcsyncd	INFO	Commencing sync process
2020-10-14T09:27:56Z	34588	MainThread	ipaserver.globalcatalog.gcsyncer	INFO	Initial LDAP dump is done, now synchronizing with GC
2020-10-14T09:29:19Z	34588	MainThread	ipa-gcsyncd	ERROR	syncrepl_poll: LDAP error ({'desc': "Can't contact LDAP server"})
2020-10-14T09:30:01Z	35366	MainThread	ipa-gcsyncd	INFO	LDAP bind...
2020-10-14T09:30:01Z	35366	MainThread	ipa-gcsyncd	INFO	Commencing sync process
2020-10-14T09:30:01Z	35366	MainThread	ipaserver.globalcatalog.gcsyncer	INFO	Initial LDAP dump is done, now synchronizing with GC

```

**Comment by flo-renaud** [comment]
Syncrepl is used in "refreshAndPersist" mode, and the message simply means that it's moving from refresh to persist stage. If the daemon was started with a cookie, and the state hasn't changed, no notification is sent in the refresh stage and the daemon can move to the persist stage. If there were changes since the cookie, they are sent and then the daemon can move to the persist stage.
The message doesn't imply that the daemon re-read the whole dataset (the initial "dump" means a diff between stored cookie and now). If you find it misleading, it can be changed. Any suggestion?

**Comment by wladich** [comment]
Couple of questions not related to issue, just for better understanding:
1. Is it the refresh phase of the "refreshAndPersist" what is used for creating records in GC instance during first run of "ipa-adtrust-install "?
2. Should there be any differences in log messages during sync daemon startup with and without changes in main instance? (I do not see any differences now)

**Comment by flo-renaud** [comment]
> Is it the refresh phase of the "refreshAndPersist" what is used for creating records in GC instance during first run of "ipa-adtrust-install "?

Yes. But records can also be created during the persist stage.

> Should there be any differences in log messages during sync daemon startup with and without changes in main instance? (I do not see any differences now)

It depends on what happened between the last cookie and the daemon startup.
For instance:
- case A: daemon is stopped, 3 new users added (u1, u2, u3), daemon is started, user u1 deleted, user u4 added: you should see in the refresh stage the logs for the 3 new users, then "initial dump done", then u1 deletion, u4 addition
- case B: daemon is stopped, 3 new users added (u1, u2, u3), user u1 is deleted, daemon is started, user u4 added: you should see in the refresh stage the logs for 2 new users (u2 and u3), then "initial dump done", then u4 addition

**Comment by wladich** [comment]
Thank you, I have enabled debug in globalcatalog.conf and now I see the messages. I see that a newly created user is being updated on every daemon start but I guess it is another problem, I will report it in separate issue.

**Comment by abbra** [comment]
May be we should move 'initial dump' message from INFO to DEBUG?

**Comment by wladich** [comment]
Well, after explanations the message looks sane. I prefer to keep it as INFO because it marks the position in log where first phase ends: if we see ERROR messages, we can immediately see if they happened during this initial phase.

**Comment by flo-renaud** [comment]
@wladich fedora 32 now ships python-ldap 3.3.1-1 (see https://bodhi.fedoraproject.org/updates/FEDORA-2020-9c484c6e2b), meaning that the issue shouldn't happen any more. Can you check and close the issue if it's OK?

**Comment by wladich** [comment]
Yes, it works now
```
# rpm -q python3-ldap
python3-ldap-3.3.1-1.fc32.x86_64
```

```
# ipa-adtrust-install -U -a Secret123 --add-sids
...
# cat /var/lib/ipa/gc_cookie
cat: /var/lib/ipa/gc_cookie: No such file or directory
# ipactl restart
...
# cat /var/lib/ipa/gc_cookie
master1.testrelm.test:389#cn=Directory Manager:cn=accounts,dc=testrelm,dc=test:(|(objectClass=groupofnames)(objectClass=person))#160
```
