### ISSUE TITLE
gc-wip: Inconsistent case in LDAP attribute values 

### ISSUE THREAD

**Issue by wladich** [abbra/freeipa#59]
Example: Inconsistent case in “cn=users”.

dn: CN=idmgroup3,cn=users,dc=testrelm,dc=test
...
memberOf: cn=ipausers,cn=users,dc=testrelm,dc=test
...
member: CN=First User,CN=Users,dc=testrelm,dc=test

**Comment by flo-renaud** [comment]
Should be easy to fix as the cases are set in the templates, see for instance: https://github.com/abbra/freeipa/blob/gc-wip/ipaserver/globalcatalog/templates/gc_user_template.tmpl#L4 and https://github.com/abbra/freeipa/blob/gc-wip/ipaserver/globalcatalog/templates/gc_group_template.tmpl#L1
Except for consistency there shouldn't be any consequence to the different case (attribute names are case-insensitive and cn or CN should be  handled identically).

**Comment by wladich** [comment]
Issue is fixed
