### ISSUE TITLE
gc-wip: some user login formats are not supported for autologon

### ISSUE THREAD

**Issue by wladich** [abbra/freeipa#65]
Tested with autologon Windows feature ([link](https://support.microsoft.com/en-us/help/324737/how-to-turn-on-automatic-logon-in-windows)) on AD controller and client machines.

I have also checked that all used login formats work for non-admin AD user.

With DefaultDomainName
-----------------------------------
DefaultUserName | DefaultDomainName | Login works
-- | -- | --
logintest | testrelm.test | -
logintest | TESTRELM.TEST | +
logintest|Testrelm.Test|-
logintest | testrelm | -
logintest | TESTRELM | -
logintest | Testrelm | -
LOGINTEST|TESTRELM.TEST|+
Logintest|TESTRELM.TEST|+

Without DefaultDomainName
---------------------------------------
DefaultUserName | Login works
--|--
logintest@testrelm.test |  +
logintest@TESTRELM.TEST |  +
logintest@Testrelm.Test  | +
logintest@testrelm |  -
logintest@TESTRELM|  -
logintest@Testrelm |  -
testrelm.test\logintest |  -
TESTRELM.TEST\logintest |  +
Testrelm.Test\logintest |  -
testrelm\logintest |  -
TESTRELM\logintest |  -
Testrelm\logintest |  -
LOGINTEST@ipa.test|+
Logintest@ipa.test|+
IPA.TEST\LOGINTEST|+
IPA.TEST\Logintest|+

In all cases when login fails, Windows displays message "The user name or password is incorrect. Try again"

Is GC supposed to support all of those login formats?

**Comment by wladich** [comment]
Update: added mixed-case domain names and variants of user name in upper case

**Comment by wladich** [comment]
The table "Without DefaultDomainName" also applies to WinRM logons from Windows to Windows:
* using `winrs` command, credentials provided with `-u:` and `-p:` options
* using `Invoke-Command` PowerShell scriptlet, credentials provided as `PSCredential` object in `-Credentials`option

**Comment by abbra** [comment]
Moved this ticket to https://pagure.io/freeipa/issue/8733
