### ISSUE TITLE
Does not work on fedora 36

### ISSUE THREAD

**Issue by alealexpro100** [abbra/freeipa#93]
I managed to install freeipa server from CORP repo `abbra/gc-wip`, but when I run `ipa-server-install -a Password123 -p Password123 --domain=ipadomain.ipa --realm=IPADOMAIN.IPA --setup-dns --no-forwarders -U` it fails on `[16/41]: creating indices` with `[error] KeyError: 'REALM'`.

I somehow bypassed it by editing 237th line in file `/usr/lib/python3.10/site-packages/ipaserver/install/ldapupdate.py` by replacing `self.sub_dict["REALM"]` with `api.env.realm` but it doesn't look like it's good idea.

Log of installation: [ipaserver-install.log](https://github.com/abbra/freeipa/files/9166116/ipaserver-install.log).

**Comment by abbra** [comment]
I pushed an update that rebases on top of FreeIPA master and fixes this problem as well, the build is ongoing. Thank you for the report.

**Comment by alealexpro100** [comment]
Checked. Not is it working. Thank you.
